---
version: '3.8'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
      - '--web.config=/etc/node-exporter/web-config.yml'
      - '--no-collector.powersupplyclass'
    network_mode: host
    pid: host
    restart: unless-stopped
    env_file:
      - tz.env
    volumes:
      - '/:/host:ro,rslave'
      - './web-config.yml:/etc/node-exporter/web-config.yml:ro'
      - './certs:/etc/node-exporter/certs:ro'
