---
# tasks file for loki
- name: create group
  group: name=loki system=true state=present

- name: create user
  user: name=loki system=true shell=/usr/sbin/nologin group=loki createhome=false home={{install_dir}}

- name: secure dir
  file:
    path: "{{install_dir}}"
    state: directory
    owner: loki
    group: loki
    mode: 0700

- name: create dir
  file:
    path: "{{install_dir}}/{{item}}"
    state: directory
    owner: loki
    group: loki
  with_items:
    - bin
    - etc
    - lib
    - data

- name: check version
  command: "{{install_dir}}/bin/loki-linux-amd64 -version"
  failed_when: false
  changed_when: false
  register: check_version

- name: download loki
  unarchive:
    remote_src: yes
    src: https://github.com/grafana/loki/releases/download/{{ loki_version }}/loki-linux-amd64.zip
    dest: "{{install_dir}}/bin/"
    mode: '+x'
  when: check_version.stdout is not defined

- name: copy templates
  template:
    src: loki-config.yml
    dest: "{{install_dir}}/etc/"

- name: create service file
  template:
    src: loki.service
    dest: /etc/systemd/system/{{service_name}}.service

- name: start service
  systemd: name={{service_name}} state=started enabled=yes daemon_reload=yes

- name: test service
  uri:
    url: http://localhost:3100/ready
    return_content: true
    remote_src: true
  register: response
  retries: 3
  delay: 30
  failed_when: "'ready' not in response.content"